import { Metadata } from "next"


export const metadata: Metadata = {
  title: "About | Next App", // Sa mer projecti anunna dnm browseri tab-i mej
  description: "Generated by create next app",
}


export default function About() {
    return <h1>Select sub item</h1>
  }