import { Metadata } from "next"
import Link from "next/link"

async function getData() {
  const response = await fetch("https://jsonplaceholder.typicode.com/posts",{
    next:{
      revalidate:60 // amen 60 vayrkyan@ mek mi hat harcum ara tes nor post ka, te che
    }
  })

if (!response.ok) throw new Error("unable to fetch posts")


  return response.json()
}

export const metadata: Metadata = {
  title: "Blog | Next App", // Sa mer projecti anunna dnm browseri tab-i mej
  description: "Generated by create next app",
}

export default async function Blog() {
  const posts = await getData()
  return (
    <>
      <h1>Blog page</h1>
      <ul>
        {posts.map((post: any) => (
          <li key={post.id}>
            <Link href={`/blog/${post.id}`}>{post.title}</Link>
          </li>
        ))}
      </ul>
    </>
  )
}
